version: '3.3'

volumes:
  pg_data:
  static:
  media:
  static_frontend:

services:
  db:
    image: postgres:13.10
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file:
      - ../backend/.env
    volumes:
      - static:/app/static_django/
      - media:/app/media/
      - ../data:/app/data 
    depends_on:
      - db

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/build:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/static_django/
      - media:/media/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - ../frontend/build:/usr/share/nginx/html/
    depends_on:
      - backend
      - frontend