# Generated by Django 4.2.16 on 2024-10-24 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_alter_favorite_options_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='text',
        ),
    ]
