# Generated by Django 4.2.16 on 2024-10-24 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0003_rename_description_recipe_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_favorited',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_in_shopping_cart',
        ),
    ]
