# Generated by Django 4.2.16 on 2024-10-26 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0004_remove_recipe_is_favorited_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_subscribed',
        ),
    ]
