# Generated by Django 4.2.16 on 2024-10-27 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0005_remove_user_is_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_link_hash',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
