# Generated by Django 4.2.16 on 2024-10-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0005_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_subscription',
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'subscribed_to')},
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user', 'subscribed_to'), name='unique_user_subscription'),
        ),
    ]
