# Generated by Django 4.2.16 on 2024-10-17 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0006_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_user_subscription',
        ),
    ]
