# Generated by Django 4.2.16 on 2024-10-17 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0007_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_favorite_recipe',
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'recipe')},
        ),
        migrations.AlterModelTable(
            name='favorite',
            table=None,
        ),
    ]
