# Generated by Django 4.2.16 on 2024-10-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0009_alter_favorite_unique_together_alter_favorite_recipe_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user', 'subscribed_to'), name='unique_subscription'),
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='created_at',
        ),
    ]
